# Generated by Django 3.0.7 on 2020-06-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ids',
            field=models.CharField(max_length=250),
        ),
    ]
